name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, v2 ]
  pull_request:
    branches: [ main, master, v2 ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create model file
      run: python train_model.py
    
    - name: Test application
      run: |
        python -c "
        from app import app
        import tempfile
        import os
        
        # Test app creation
        assert app is not None
        print('App created successfully')
        
        # Test model loading
        from app import model
        assert model is not None
        print('Model loaded successfully')
        
        print('✅ All tests passed!')
        "

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        docker build -t credit-risk-app .
        echo "Docker build successful"
    
    - name: Test Docker container
      run: |
        # Start container in background
        docker run -d -p 5000:5000 -e PORT=5000 --name test-container credit-risk-app
        
        # Wait for container to start
        sleep 10
        
        # Test if container is running
        docker ps | grep test-container
        
        # Cleanup
        docker stop test-container
        docker rm test-container
        
        echo "Docker container test successful"
